import type { Metadata } from 'next'

import './globals.css'
import ProviderWrapper from '@/components/layout/provider-wrapper'
import Footer from '@/components/footer/footer'
import PageWrapper from '@/components/layout/page-wrapper'
import Header from '@/components/navbar/header'
import ThemeModeBtn from '@/components/theme-mode-btn'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactElement
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderWrapper>
          <PageWrapper>
            <div className="flex min-h-screen flex-col">
              <Header />
              <main className="flex-1">{children}</main>
              <ThemeModeBtn />
              <Footer />
            </div>
          </PageWrapper>
        </ProviderWrapper>
      </body>
    </html>
  )
}
